apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: h7j2q17mz-nodejs 
  janus-idp.io/tekton: h7j2q17mz-nodejs
  backstage.io/kubernetes-id: h7j2q17mz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h7j2q17mz-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml