apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: h7j2q17mz-nodejs-gitops
  description: This is GitOps manifest for h7j2q17mz-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=h7j2q17mz-nodejs
    backstage.io/kubernetes-id: h7j2q17mz-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: h7j2q17mz-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:h7j2q17mz-nodejs
